# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2945ef7ff1541e154cdbda36adc1400412f77e3805ab6618782b630844bd1266b642f49af1d30ff88e94b57b5abc1a3656c693a00b4accdc90d43f018bb0fe34

test:
  secret_key_base: 235c69186a0b78fe087de032e4210535822244fae6d02fc8eebacfcaf534e9ceec0011c643b9af9e164cb44d83810fff604f1e856eb769f2b1292d7e4599dd52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
